baseURL = "https://docs.plaidcloud.io"
title = "PlaidCloud"

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
disableBrowserError = true

disableKinds = ["taxonomy", "taxonomyTerm"]

ignoreFiles = [ "(?:^|/)OWNERS$", "README[-]+[a-z]*\\.md", "^node_modules$", "content/en/docs/doc-contributor-tools" ]

timeout = 3000

# Highlighting config.
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

# Norwegian ("no") is sometimes but not currently used for testing.
# Hindi is disabled because it's currently in development.
disableLanguages = ["es", "de", "hi", "no", "fr", "id", "it", "ja", "ko", "pl", "pt-br", "ru", "uk", "vi", "zh"]

[caches]
 [caches.assets]
  dir = ":cacheDir/_gen"
  maxAge = -1
 [caches.getcsv]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.getjson]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.images]
  dir = ":cacheDir/_images"
  maxAge = -1
 [caches.modules]
  dir = ":cacheDir/modules"
  maxAge = -1

[markup]
 [markup.goldmark]
   [markup.goldmark.extensions]
     definitionList = true
     table = true
     typographer = false
   [markup.goldmark.parser]
     attribute = true
     autoHeadingID = true
     autoHeadingIDType = "blackfriday"
   [markup.goldmark.renderer]
     unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[sitemap]
  filename = "sitemap.xml"
  priority = 0.75

# Be explicit about the output formats. We (currently) only want an RSS feed for the home page.
[outputs]
home = [ "HTML", "RSS", "HEADERS" ]
page = [ "HTML"]
section = [ "HTML", "print" ]

# Add a "text/netlify" media type for auto-generating the _headers file
[mediaTypes]
[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats]
[outputFormats.RSS]
baseName = "feed"

# _headers file output (uses the template at layouts/index.headers)
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-53330916-3"

[params]
copyright_plaidcloud = "Copyright © 2022 Tartan Solutions, Inc | PlaidCloud ®"

# privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Versions"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 02, 2006 at 3:04 PM EST"

description = "Unified Financial Analytics Solution"
showedit = true

latest = "v5.8"

fullversion = "v5.10.1"
version = "v5.10"
githubbranch = "main"
docsbranch = "main"
deprecated = false
currentUrl = "https://docs.plaidcloud.io/"
nextUrl = "https://PlaidCloud-io-vnext-staging.netlify.com/"

# See codenew shortcode
githubWebsiteRaw = "raw.githubusercontent.com/plaidcloud/website"

# GitHub repository link for editing a page and opening issues.
github_repo = "https://github.com/plaidcloud/website"

#Searching
plaidcloud_search = true

#The following search parameters are specific to Docsy's implementation. PlaidCloud implementes its own search-related partials and scripts.

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "ee7b3fb393a7e3b28"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

[params.pushAssets]
css = [
  "callouts",
  "styles"
]
js = [
  "script"
]

[[params.versions]]
fullversion = "Production"
version = "Production"
docsbranch = "main"
url = "https://docs.plaidcloud.com"

[[params.versions]]
fullversion = "Beta"
version = "Beta"
# githubbranch = "v1.22.4"
docsbranch = "release-5.9"
url = "https://docs.plaidcloud.net"

[[params.versions]]
fullversion = "Development"
version = "Development"
# githubbranch = "v1.21.7"
docsbranch = "release-5.8"
url = "https://docs.plaidcloud.io"


# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# https://github.com/gohugoio/hugo/issues/8918#issuecomment-903314696
sidebar_cache_limit = 1
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "LinkedIn"
	url = "https://www.linkedin.com/company/plaidcloud"
	icon = "fab fa-linkedin"
  desc = "Connect with us on LinkedIn"

[[params.links.user]]
	name = "Twitter"
	url = "https://twitter.com/plaidcloud"
	icon = "fab fa-twitter"
  desc = "Follow us on Twitter to get the latest news!"

[[params.links.user]]
	name = "Youtube"
	url = "https://youtube.com/plaidcloud"
	icon = "fab fa-youtube"
  desc = "PlaidCloud Youtube videos"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/plaidcloud"
	icon = "fab fa-github"
  desc = "Development takes place here!"

[[params.links.developer]]
	name = "Slack"
	url = "https://join.slack.com/t/plaidcloud/shared_invite/zt-13j06r9sw-AEskNx0PuOzMTOAmV2T45Q"
	icon = "fab fa-slack"
  desc = "Chat with others in the PlaidCloud community"

[[params.links.developer]]
	name = "Stack Overflow"
	url = "https://stackoverflow.com/questions/tagged/plaidcloud"
	icon = "fab fa-stack-overflow"
  desc = "Practical questions and curated answers"

# Language definitions.

[languages]
[languages.en]
title = "PlaidCloud"
description = "Unified Financial Analytics"
languageName ="English"
# Weight used for sorting.
weight = 1
languagedirection = "ltr"

[languages.zh]
title = "PlaidCloud"
description = "生产级别的容器编排系统"
languageName = "中文 Chinese"
weight = 2
contentDir = "content/zh"
languagedirection = "ltr"

[languages.zh.params]
time_format_blog = "2006.01.02"
language_alternatives = ["en"]

[languages.ko]
title = "PlaidCloud"
description = "운영 수준의 컨테이너 오케스트레이션"
languageName = "한국어 Korean"
weight = 3
contentDir = "content/ko"
languagedirection = "ltr"

[languages.ko.params]
time_format_blog = "2006.01.02"
language_alternatives = ["en"]

[languages.ja]
title = "PlaidCloud"
description = "プロダクショングレードのコンテナ管理基盤"
languageName = "日本語 Japanese"
weight = 4
contentDir = "content/ja"
languagedirection = "ltr"

[languages.ja.params]
time_format_blog = "2006.01.02"
language_alternatives = ["en"]

[languages.fr]
title = "PlaidCloud"
description = "Solution professionnelle d’orchestration de conteneurs"
languageName ="Français"
weight = 5
contentDir = "content/fr"
languagedirection = "ltr"

[languages.fr.params]
time_format_blog = "02.01.2006"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]

[languages.it]
title = "PlaidCloud"
description = "Orchestrazione di Container in produzione"
languageName = "Italiano"
weight = 6
contentDir = "content/it"
languagedirection = "ltr"

[languages.it.params]
time_format_blog = "02.01.2006"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]

[languages.no]
title = "PlaidCloud"
description = "Production-Grade Container Orchestration"
languageName ="Norsk"
weight = 7
contentDir = "content/no"
languagedirection = "ltr"

[languages.no.params]
time_format_blog = "02.01.2006"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]

[languages.de]
title = "PlaidCloud"
description = "Produktionsreife Container-Orchestrierung"
languageName ="Deutsch"
weight = 8
contentDir = "content/de"
languagedirection = "ltr"

[languages.de.params]
time_format_blog = "02.01.2006"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]

[languages.es]
title = "PlaidCloud"
description = "Orquestación de contenedores para producción"
languageName ="Español"
weight = 9
contentDir = "content/es"
languagedirection = "ltr"

[languages.es.params]
time_format_blog = "02.01.2006"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]

[languages.pt-br]
title = "PlaidCloud"
description = "Orquestração de contêineres em nível de produção"
languageName ="Português"
weight = 9
contentDir = "content/pt-br"
languagedirection = "ltr"

[languages.pt-br.params]
time_format_blog = "02.01.2006"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]

[languages.id]
title = "PlaidCloud"
description = "Orkestrasi Kontainer dengan Skala Produksi"
languageName ="Bahasa Indonesia"
weight = 10
contentDir = "content/id"
languagedirection = "ltr"

[languages.id.params]
time_format_blog = "02.01.2006"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]

[languages.hi]
title = "PlaidCloud"
description = "Production-Grade Container Orchestration"
languageName = "Hindi"
weight = 11
contentDir = "content/hi"
languagedirection = "ltr"

[languages.hi.params]
time_format_blog = "01.02.2006"
language_alternatives = ["en"]

[languages.vi]
title = "PlaidCloud"
description = "Giải pháp điều phối container trong môi trường production"
languageName = "Tiếng Việt"
contentDir = "content/vi"
weight = 12
languagedirection = "ltr"

[languages.ru]
title = "PlaidCloud"
description = "Первоклассная оркестрация контейнеров"
languageName = "Русский"
weight = 12
contentDir = "content/ru"
languagedirection = "ltr"

[languages.ru.params]
time_format_blog = "02.01.2006"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]

[languages.pl]
title = "PlaidCloud"
description = "Produkcyjny system zarządzania kontenerami"
languageName = "Polski"
weight = 13
contentDir = "content/pl"
languagedirection = "ltr"

[languages.pl.params]
time_format_blog = "01.02.2006"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]

[languages.uk]
title = "PlaidCloud"
description = "Довершена система оркестрації контейнерів"
languageName = "Українська"
weight = 14
contentDir = "content/uk"
languagedirection = "ltr"

[languages.uk.params]
time_format_blog = "02.01.2006"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$", ".png$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "hugo-gcs"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
URL = "gs://plaidcloud-docs-website-io"


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# See https://golang.org/pkg/regexp/syntax/ for pattern syntax.
# Pattern searching is stopped on first match.

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true