apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app.PlaidCloud.io/name: mongo
    app.PlaidCloud.io/component: backend
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.PlaidCloud.io/name: mongo
    app.PlaidCloud.io/component: backend
